apiVersion: extensions.agents.x-k8s.io/v1alpha1
kind: SandboxWarmPool
metadata:
  name: dog-agent-warmpool
  namespace: barkland
spec:
  replicas: 10
  sandboxTemplateRef:
    name: dog-agent-template
